Repository Professional-Hobo/lame-corner-bot, pull requests merged in 2020-07, with the labels that each got.

#6 Moved some code for prompting a user to utils so it can be used by ot…
  commands/misc/msg.js
  lib/utils.js
Labels: enhancement

#5 Add rolesmsg command
  commands/mod/rolesmsg.js
  example.env
  index.js
Labels: command

#20 Add/Edit commands accept regular emojis. Fixes #17
  commands/mod/rolesmsg.js
  package-lock.json
  package.json
Labels: bug
